# 2022-1학기 기말평가
- 딥러닝 수학

## 1. Matrix Multiplication 코드를 작성하고 "MML_Exam_1.py"로 저장 후 제출
- 조건 1) 라이브러리 사용하지 말고 수현할 것
- 조건 2) n x m 메트릭스 생성 후, n x m * m x n = n x n 의 결과가 나오도록 입력 데이터 생성할 것
    - 입력 데이터 생성하는 부분은 함수로 작성
    - n, m : >= 3 and <= 20
    - ```*``` : matrix multiplication (Not element-wise multiplication)
- np.random.seed(8)로 셋팅해 동일한 랜덤 값이 출력되도록 하고, 최종 6 x 6 결과를 작성할 것


### 코드 제출 전 Octave Online을 통해 3x3 matrix 곱하기 결과 먼저 확인해볼 것!

```python
# Template Code
import numpy as np

np.random.seed(8)

def gen_data(mat, n, m):
    for i in range(n):
        '''
        채우기
        '''
        
def matmul(mat1, mat2, result):
    for i in range(len(mat1)):
        '''
        채우기
        '''
        
if __name__ == "__main__":
    '''
    채우기
    '''
    
    n = np.random.randint(3, 20)
    m = np.random.randint(3, 20)
    
    print(n, m)
    
    mat1 = np.zeros((n, m))
    mat2 = np.zeros((m, n))
    result = np.zeros((n, n))
    
    gen_data(mat1, n, m)
    gen_data(mat2, m, n)
    matmul(mat1, mat2, result)
    
    print(result, result.shape)
```

In [21]:
import numpy as np
np.random.seed(8)


def gen_data(mat, n, m):
    '''
    mat = n x m matrix 생성
    '''
    for i in range(n):
        for j in range(m):
            mat[i][j] = np.random.randint(0, 10)
        
    
def matmul(mat1, mat2, result):
    '''
    element-wise가 아닌 matrix mulitplication 함수
    n x m * m x n = n x n 반환
    '''
    for i in range(len(result)):
        for j in range(len(result[i])):
            for k in range(len(mat1[i])):
                result[i][j] += mat1[i][k] * mat2[k][j]
        
        
if __name__ == "__main__":    
    n = np.random.randint(3, 20)
    m = np.random.randint(3, 20)
    
    print(n, m)
    
    mat1 = np.zeros((n, m))
    mat2 = np.zeros((m, n))
    result = np.zeros((n, n))
    
    gen_data(mat1, n, m)
    gen_data(mat2, m, n)
    matmul(mat1, mat2, result)
    
    # print(mat1)
    # print(mat2)
    print(result, result.shape)

6 12
[[182. 277. 266. 202. 324. 172.]
 [273. 434. 402. 341. 387. 184.]
 [233. 300. 296. 219. 305. 176.]
 [251. 364. 348. 308. 356. 228.]
 [205. 295. 244. 176. 255. 102.]
 [286. 419. 350. 336. 405. 196.]] (6, 6)


## 2. DB에는 총 101개의 문서가 존재하고, DB에 저장된 문서를 모두 Vectorization을 수행하였다. 첫 번째 문서의 vectorization 결과는 다음과 같았다.

```vec_doc_1 = [0.2, 0.4, 0.02, 0.1, 0.9, 0.8]```

100개의 문서 중 첫 번째 문서와 가장 유사한 문서를 검색하는 코드를 작성하고, "MML_Exam_2.py"로 저장하여 제출하시오
- 조건 1) 100 x 6 array를 만들고 np.random.seed(1234)로 랜덤 값이 고정으로 출력되게 세팅 후, np.random.random() 함수를 사용하여 각 컬럼의 값을 랜덤하게 생성
- 조건 2) Inner Production을 이용하여 가장 유사도가 높은 문서(row)를 선택할 것
    - Inner Production을 이용하는 부분은 함수로 만들 것
    - 출력 : (인덱스, 값)
    - 값은 소수점 3째 자리에서 반올림 ex) 0.2456 -> 0.25

```python
# Template Code
import numpy as np

def inner_product(vectors, in_vec):
    max = (0, 0)
    for i in range(len(vectors)):
        '''
        채우기
        '''
    return max
    
if __name__ == "__main__":
    np.random.seed(1234)
    doc_vec = np.zeros((100, 6))
    for i in range(100):
        '''
        채우기
        '''
    
    # print(doc_vec)
    
    vec_doc_1 = [0.2, 0.4, 0.02, 0.1, 0.9, 0.8]
    
    print(inner_product(doc_vec, vec_doc_1))
```

In [70]:
import numpy as np

def inner_product(vectors, in_vec):
    '''
    vectors 중 in_vec와 가장 유사한 row를 (인덱스, 값) 형태로 반환
    '''
    max_similar = (0, 0)  # (idx, [round(val, 3) for val in row])
    
    for i in range(len(vectors)):
        inner_p = np.inner(vectors[i], in_vec)
        if inner_p > max_similar[1]:
            max_similar = (i, round(inner_p, 2))
            # print(vectors[i])
        
    return max_similar
    
    
if __name__ == "__main__":
    np.random.seed(1234)
    
    doc_vec = np.zeros((100, 6))
    for i in range(100):
        for j in range(6):
            doc_vec[i][j] = np.random.random()
    
    # print(doc_vec, doc_vec.shape)
    
    vec_doc_1 = [0.2, 0.4, 0.02, 0.1, 0.9, 0.8]
    
    print(inner_product(doc_vec, vec_doc_1))

(9, 2.1)


## 3. 입력층에 있는 Weight들이 출력 층의 Error에 미치는 영향을 계산하기 위해서 Chain-Rule을 이용한 Backpropagation을 수행하여야 한다.
다음과 같은 신경망이 주어졌을 때, Backpropagation에 의해 업데이트되는 Weight 들을 구하는 코드를 작성하고, "MML_Exam_3.py"로 저장하여 제출하시오.  
(실제 코드 작성 시에는 다음과 같이 세팅 후 계산 결과 도출할 것   
```W1 = 0.2, W2 = 0.23, W3 = 0.38, W4 = 0.35, W5 = 0.42, W6 = 0.32, W7 = 0.64, W8 = 0.6```)  
- 조건 1) Weight 5, 6, 7, 8이 Total Error에 미치는 영향을 구하는 코드만 작성하시오 (Backpropagation 1단계)
- 조건 2) Forward phase에서 계산되어지는 값은 미리 계산해놓고, z3, z4를 W5, W6, W7, W8로 편미분한 값도 미리 계산해놓는다
- 조건 3) Sigmoid 함수는 별도로 만들어서 사용하며, Learning Rate값은 0.5로 세팅한다.


```python
# Template Code
import numpy as np

def sigmoid(val):
    '''
    채우기
    '''
    
lr = 0.5

x1, x2 = 0.1, 0.2

'''
채우기
'''

z3 = w5*h1 + w6*h2
dz3_w5 = h1
dz3_w6 = h2

z4 = w7*h1 + w8*h2
dz4_w7 = h1
dz4_w8 = h2

o1 = sigmoid(z3)
o2 = sigmoid(z4)

Eo1 = 0.5*(target_o1 - o1)**2
Eo2 = 0.5*(target_o2 - o2)**2
Etotal = Eo1 + Eo2

print(z1, z2, h1, h2, z3, z4, o1, o2, Etotal)


def backpropagation_1(weight, d_weight, target, output):
    '''
    채우기
    '''
    
if __name__ == "__main__":
    print(backpropagation_1(w5, dz3_w5, target_o1, o1))
    print(backpropagation_1(w6, dz3_w6, target_o1, o1))    
    
    # 업데이트된 Weights(W5~W8) 작성
```

In [ ]:
import numpy as np

def sigmoid(val):
    '''
    채우기
    '''
    
lr = 0.5

x1, x2 = 0.1, 0.2

'''
채우기
'''

z3 = w5*h1 + w6*h2
dz3_w5 = h1
dz3_w6 = h2

z4 = w7*h1 + w8*h2
dz4_w7 = h1
dz4_w8 = h2

o1 = sigmoid(z3)
o2 = sigmoid(z4)

Eo1 = 0.5*(target_o1 - o1)**2
Eo2 = 0.5*(target_o2 - o2)**2
Etotal = Eo1 + Eo2

print(z1, z2, h1, h2, z3, z4, o1, o2, Etotal)


def backpropagation_1(weight, d_weight, target, output):
    '''
    채우기
    '''
    
if __name__ == "__main__":
    print(backpropagation_1(w5, dz3_w5, target_o1, o1))
    print(backpropagation_1(w6, dz3_w6, target_o1, o1))    
    
    # 업데이트된 Weights(W5~W8) 작성