# Pytorch 

In [1]:
import torch
import torch.nn as nn  # neural net 사용하기 위함
import torch.nn.functional as F
import torch.optim as optim  # optimizer 선택하기 위함
 
import numpy as np

In [2]:
# 입력값과 출력값
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# ▶ H(x) = Wx + b : w값과 b값을 찾기 위함

model 선언을 하고, 초기화, 단순 선형회귀,  
입력 dimension 1, 출력 dimension 1

### ▷ model 생성하게 되면 model의 값은?
model parameters : w, b

In [3]:
model = nn.Linear(1, 1)  # 입력 형태
list(model.parameters())  # 처음엔 랜덤한 값 출력됨

[Parameter containing:
 tensor([[0.3548]], requires_grad=True),
 Parameter containing:
 tensor([0.5491], requires_grad=True)]

# ▶ 최적화를 하기 위한 방법 정의
- optimizer로 경사하강법(SGD) 사용
- ```W := W - lr(gradient)```
- learning rate 설정 : ```lr=0.01```

In [4]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [5]:
# 현재 전체 데이터 셋 x_train = (1, 2, 3)에 대해 경사하강법을 얼마나 할래? 적용해보기
nb_epochs = 2000

for epoch in range(nb_epochs+1):
    # H(x) = Wx + b를 계산
    # w, b는 초기 랜덤값 pred vs. 실제값하고 얼마나 차이가 있냐를 계산
    pred = model(x_train) 
    
    # cost 계산 = Loss Function, Error 값을 계산
    cost = F.mse_loss(pred, y_train)  # (찐 - pred) 한 오차값을 제곱해서 mean square 구함
    
    # cost를 기준으로 weight, bias 값을 업데이트
    optimizer.zero_grad()  # pytorch에서 이걸 사용해야 계산된 값이 누적되지 않음. 이걸 써야 값이 갱신됨
    # -> w, b 값 업데이트
    
    # loss 값을 줄이기 : 아래 두 줄은 함께 써주기
    cost.backward()  # backward하면서 위에서 구한 weight값을 조정.
    optimizer.step()  # w, b값이 업데이트
    
    # 100번마다 log 값 출력 : 변경되는 w, b
    if epoch % 100 == 0:
        weightBias = list(model.parameters())  # 마지막값 출력 해보고 싶은데 그러려면 값을 저장해둬야 함. 그래서 생성한 변수
        print(f'Cost : {cost.item()}')  # Cost.item() : w, b 쌍으로 나옴

print(f'Final Weight, Bias : {weightBias[0]}, {weightBias[1]}')

Cost : 9.318817138671875
Cost : 0.10082312673330307
Cost : 0.06230254843831062
Cost : 0.03849911317229271
Cost : 0.023790106177330017
Cost : 0.014700808562338352
Cost : 0.00908423401415348
Cost : 0.005613468587398529
Cost : 0.0034687903244048357
Cost : 0.0021435071248561144
Cost : 0.0013245693407952785
Cost : 0.00081849773414433
Cost : 0.0005057883099652827
Cost : 0.00031254664645530283
Cost : 0.00019313330994918942
Cost : 0.00011934619396924973
Cost : 7.374708366114646e-05
Cost : 4.557210559141822e-05
Cost : 2.8160442525404505e-05
Cost : 1.740245170367416e-05
Cost : 1.0753098649729509e-05
Final Weight, Bias : Parameter containing:
tensor([[1.9962]], requires_grad=True), Parameter containing:
tensor([0.0086], requires_grad=True)


---
# ㄱㄱ

In [ ]:
A = np.array([[1, 1], [2, 1], [3, 1]])  # 3x2 Matrix
b = np.array([2, 4, 6])  # 3x1 Vector
c = np.matmul(np.matmul(np.linalg.inv(np.matmul(A.T, A)), A.T), b)  # projection = 추정값
# linalg : linear algorithm

# print(c)  # Wx+b에서 weight값과 bias 값에 해당

In [8]:
c = np.linalg.inv(np.matmul(A.T, A))  # 여기까진 문제 없음

In [ ]:
c = np.matmul(c, A.T)  # 여기서부터 kernel died