# numpy

In [7]:
import numpy as np
from matplotlib import pyplot as plt

In [4]:
a = np.array([1,2,3,4])
print(a)  # 컴마 없이 출력됨

[1 2 3 4]


In [3]:
type(a)

numpy.ndarray

In [5]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
c = np.linspace(-3.14, 3.14, 10)  # -3.14~3.14 사이를 10개의 구간으로 나누어라
c

array([-3.14      , -2.44222222, -1.74444444, -1.04666667, -0.34888889,
        0.34888889,  1.04666667,  1.74444444,  2.44222222,  3.14      ])

In [18]:
d = np.linspace(-3.14, 3.14, 100)  # -3.14~3.14 사이를 100개의 구간으로 나누어라
d

array([-3.14      , -3.07656566, -3.01313131, -2.94969697, -2.88626263,
       -2.82282828, -2.75939394, -2.6959596 , -2.63252525, -2.56909091,
       -2.50565657, -2.44222222, -2.37878788, -2.31535354, -2.25191919,
       -2.18848485, -2.12505051, -2.06161616, -1.99818182, -1.93474747,
       -1.87131313, -1.80787879, -1.74444444, -1.6810101 , -1.61757576,
       -1.55414141, -1.49070707, -1.42727273, -1.36383838, -1.30040404,
       -1.2369697 , -1.17353535, -1.11010101, -1.04666667, -0.98323232,
       -0.91979798, -0.85636364, -0.79292929, -0.72949495, -0.66606061,
       -0.60262626, -0.53919192, -0.47575758, -0.41232323, -0.34888889,
       -0.28545455, -0.2220202 , -0.15858586, -0.09515152, -0.03171717,
        0.03171717,  0.09515152,  0.15858586,  0.2220202 ,  0.28545455,
        0.34888889,  0.41232323,  0.47575758,  0.53919192,  0.60262626,
        0.66606061,  0.72949495,  0.79292929,  0.85636364,  0.91979798,
        0.98323232,  1.04666667,  1.11010101,  1.17353535,  1.23

# 인자로 함수를 받음
: C에선 function point라고 한다나봐

In [12]:
def showGraph(function, arg):
    x = arg
    y = function(x)
    plt.plot(x, y)
    plt.show()

In [13]:
showGraph(np.sin, c)

In [19]:
showGraph(np.sin, d)

In [14]:
showGraph(np.cos, c)

In [15]:
showGraph(np.tan, c)